In [16]:
import os
import pandas as pd
import io

In [10]:
#print le name sans le .sql
theme = []
for filename in os.listdir("answers"):
    if filename.endswith(".sql"):
        theme.append(filename[:-4])
print(sorted(theme))

['appartements_gb1', 'appartements_gb2', 'beverages_and_food', 'beverages_and_food_sum', 'capteur_gb1', 'capteur_gb2', 'capteur_wf1', 'capteur_wf2', 'capteur_wf3', 'capteur_wf4', 'capteur_wf5', 'capteur_wf6', 'football_case_when', 'football_cte1', 'football_cte4', 'football_cte5', 'football_gb_cte2', 'football_gb_cte3', 'furniture_wf1', 'retail_case_when1', 'retail_case_when2', 'retail_group_by1', 'retail_group_by2', 'retail_group_by3', 'retail_group_by4', 'retail_group_by5', 'salaire_wf1', 'size_and_trademark', 'ventes_cte_join5', 'ventes_group_by', 'ventes_join1', 'ventes_join2', 'ventes_join3', 'ventes_join4', 'ventes_join_gb3', 'ventes_join_gb6']

In [13]:
clients = ["Oussama", "Julie", "Chris", "Tom"]
ventes = [120, 49, 35, 23, 19, 5.99, 20, 18.77, 39, 10, 17, 12]
ventes = pd.DataFrame(ventes)
ventes.columns = ["montant"]
ventes["client"] = clients * 3

In [14]:
ventes.to_csv("data/ventes.csv", index=False)

In [17]:
size = """
size
XS
S
M
L
XL
"""

trademark = """
trademark
Nike
Asphalte
Abercrombie
Lewis
"""

size = pd.read_csv(io.StringIO(size))
size.to_csv("data/size.csv", index=False)
trademark = pd.read_csv(io.StringIO(trademark))
trademark.to_csv("data/trademark.csv", index=False)

In [21]:
beverages = """
beverage,price
Orange juice,2.5
Expresso,2
Tea,3
Cappuccino,1.6
"""

food_items = """
food_item,price
Cookie juice,2.5
Chocolatine,2
Muffin,3
Croissant,1.6
"""

beverages = pd.read_csv(io.StringIO(beverages))
beverages.to_csv('data/beverages.csv',index=False)
food_items = pd.read_csv(io.StringIO(food_items))
food_items.to_csv('data/food_items.csv', index = False)

In [20]:
furniture_data = [
    ("Chairs", "Chair 1", 5.2),
    ("Chairs", "Chair 2", 4.5),
    ("Chairs", "Chair 3", 6.8),
    ("Sofas", "Sofa 1", 25.5),
    ("Sofas", "Sofa 2", 20.3),
    ("Sofas", "Sofa 3", 30.0),
    ("Tables", "Table 1", 15.0),
    ("Tables", "Table 2", 12.5),
    ("Tables", "Table 3", 18.2),
]

# Create a pandas DataFrame from the predefined data
furniture = pd.DataFrame(furniture_data, columns=["category", "item", "weight"])
furniture.to_csv('data/furniture.csv',index = False)

In [23]:
appartement = pd.read_csv('data/appartements.csv')
appartement

,Date mutation,valeur_fonciere,No voie,Type de voie,Code voie,Voie,Code postal,Commune,Code departement,Code commune,Surface_Carrez_du_1er_lot,Nombre pieces principales,Surface terrain
0,04/01/2022,208000.0,64.0,RUE,0010,DE L ABBE BONPAIN,59700.0,MARCQ EN BAROEUL,59,378,"57,69",3.0,NaN
1,04/01/2022,113000.0,1.0,RUE,0260,GUY MOCQUET,59113.0,SECLIN,59,560,"45,72",3.0,NaN
2,03/01/2022,185000.0,22.0,RUE,8749,DE TREVISE,59000.0,LILLE,59,350,"62,83",3.0,NaN
3,04/01/2022,120350.0,132.0,RUE,7554,ROGER SALENGRO,59260.0,LILLE,59,350,"43,64",2.0,NaN
4,04/01/2022,149000.0,7.0,ALL,3430,DES COLOMBIERS,59650.0,VILLENEUVE-D'ASCQ,59,9,"59,02",2.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
20659,18/02/2022,400000.0,8.0,RUE,1540,STE ALDEGONDE,62500.0,SAINT OMER,62,765,NaN,2.0,204.0
20660,18/02/2022,400000.0,8.0,RUE,1540,STE ALDEGONDE,62500.0,SAINT OMER,62,765,NaN,2.0,204.0
20661,18/02/2022,400000.0,8.0,RUE,1540,STE ALDEGONDE,62500.0,SAINT OMER,62,765,NaN,2.0,204.0
20662,18/02/2022,400000.0,8.0,RUE,1540,STE ALDEGONDE,62500.0,SAINT OMER,62,765,NaN,2.0,204.0
20663,18/02/2022,400000.0,8.0,RUE,1540,STE ALDEGONDE,62500.0,SAINT OMER,62,765,NaN,2.0,204.0

In [25]:
appartement.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20664 entries, 0 to 20663
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Date mutation              20664 non-null  object
 1   valeur_fonciere            20664 non-null  float64
 2   No voie                    20346 non-null  float64
 3   Type de voie               20370 non-null  object
 4   Code voie                  20664 non-null  object
 5   Voie                       20664 non-null  object
 6   Code postal                20664 non-null  float64
 7   Commune                    20664 non-null  object
 8   Code departement           20664 non-null  int64
 9   Code commune               20664 non-null  int64
 10  Surface_Carrez_du_1er_lot  5649 non-null   object
 11  Nombre pieces principales  20663 non-null  float64
 12  Surface terrain            8129 non-null   float64
dtypes: float64(5), int64(2), object(6)
memory usage: 2.0+ MB

In [27]:
appartement['Surface_Carrez_du_1er_lot'] = appartement['Surface_Carrez_du_1er_lot'].str.replace(',', '.').astype(float)

In [28]:
appartement

,Date mutation,valeur_fonciere,No voie,Type de voie,Code voie,Voie,Code postal,Commune,Code departement,Code commune,Surface_Carrez_du_1er_lot,Nombre pieces principales,Surface terrain
0,04/01/2022,208000.0,64.0,RUE,0010,DE L ABBE BONPAIN,59700.0,MARCQ EN BAROEUL,59,378,57.69,3.0,NaN
1,04/01/2022,113000.0,1.0,RUE,0260,GUY MOCQUET,59113.0,SECLIN,59,560,45.72,3.0,NaN
2,03/01/2022,185000.0,22.0,RUE,8749,DE TREVISE,59000.0,LILLE,59,350,62.83,3.0,NaN
3,04/01/2022,120350.0,132.0,RUE,7554,ROGER SALENGRO,59260.0,LILLE,59,350,43.64,2.0,NaN
4,04/01/2022,149000.0,7.0,ALL,3430,DES COLOMBIERS,59650.0,VILLENEUVE-D'ASCQ,59,9,59.02,2.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
20659,18/02/2022,400000.0,8.0,RUE,1540,STE ALDEGONDE,62500.0,SAINT OMER,62,765,NaN,2.0,204.0
20660,18/02/2022,400000.0,8.0,RUE,1540,STE ALDEGONDE,62500.0,SAINT OMER,62,765,NaN,2.0,204.0
20661,18/02/2022,400000.0,8.0,RUE,1540,STE ALDEGONDE,62500.0,SAINT OMER,62,765,NaN,2.0,204.0
20662,18/02/2022,400000.0,8.0,RUE,1540,STE ALDEGONDE,62500.0,SAINT OMER,62,765,NaN,2.0,204.0
20663,18/02/2022,400000.0,8.0,RUE,1540,STE ALDEGONDE,62500.0,SAINT OMER,62,765,NaN,2.0,204.0

In [42]:
appart_columns = appartement.columns.str.replace(' ', '_')
appart_columns

Index(['Date_mutation', 'valeur_fonciere', 'No_voie', 'Type_de_voie',
       'Code_voie', 'Voie', 'Code_postal', 'Commune', 'Code_departement',
       'Code_commune', 'Surface_Carrez_du_1er_lot',
       'Nombre_pieces_principales', 'Surface_terrain'],
      dtype='object')

In [41]:
appart_columns

Index(['Date mutation', 'valeur_fonciere', 'No voie', 'Type de voie',
       'Code voie', 'Voie', 'Code postal', 'Commune', 'Code departement',
       'Code commune', 'Surface_Carrez_du_1er_lot',
       'Nombre pieces principales', 'Surface terrain'],
      dtype='object')

In [43]:
appartement = appartement.rename(columns=lambda x: x.replace(' ', '_'))

In [44]:
appartement.to_csv('data/appartements.csv', index=False)

In [34]:
football = pd.read_csv("data/football.csv")
football

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,BbMx>2.5,BbAv>2.5,BbMx<2.5,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA
0,F1,07/08/10,Auxerre,Lorient,2,2,D,1,1,D,...,2.60,2.44,1.55,1.51,13,-0.50,1.90,1.83,2.03,1.94
1,F1,07/08/10,Lens,Nancy,1,2,A,0,1,A,...,2.58,2.35,1.60,1.54,11,0.00,1.50,1.42,2.85,2.67
2,F1,07/08/10,Lyon,Monaco,0,0,D,0,0,D,...,2.16,2.06,1.80,1.72,12,-1.25,2.09,2.01,1.84,1.79
3,F1,07/08/10,Marseille,Caen,1,2,A,0,0,D,...,1.84,1.75,2.12,2.00,9,-1.75,2.21,2.18,1.76,1.74
4,F1,07/08/10,Nice,Valenciennes,0,0,D,0,0,D,...,2.32,2.24,1.67,1.59,11,0.00,1.50,1.44,2.75,2.58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,F1,29/05/11,Lorient,Auxerre,1,2,A,1,1,D,...,2.10,2.00,1.80,1.73,20,-0.25,2.14,2.09,1.83,1.78
376,F1,29/05/11,Monaco,Lyon,0,2,A,0,0,D,...,2.00,1.94,1.91,1.79,17,0.25,1.85,1.80,2.11,2.04
377,F1,29/05/11,Nancy,Lens,4,0,H,2,0,H,...,1.83,1.76,2.14,2.02,20,-1.00,1.73,1.69,2.30,2.21
378,F1,29/05/11,St Etienne,Paris SG,1,1,D,0,0,D,...,1.83,1.78,2.14,2.00,20,0.50,2.17,2.13,1.79,1.76
379,F1,29/05/11,Valenciennes,Nice,2,1,H,0,0,D,...,2.22,2.11,1.75,1.70,20,-0.50,1.95,1.92,1.98,1.95

In [38]:
(football[['Date','HomeTeam','AwayTeam','FTHG','FTAG']]
.rename(columns={'FTHG':'GoalsHomeTeam','FTAG':'GoalsAwayTeam'})
.to_csv('data/football.csv',index=False)
)